theme: jekyll-theme-minimal
title: "Bui Vinh Loc - Portfolio"
logo: "assets/img/logo.png"
description: "A portfolio showcasing my skills, projects, and experience in AI and software development."
show_downloads: true
google_analytics:
