theme: jekyll-theme-minimal
title: "Bui Vinh Loc - Portfolio"
logo: "assets/img/logo.png"
description: "A website showcasing my skills, projects, and experience in software development and artificial intelligence."
google_analytics:
